//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAMENFINALPROGRAMACIONWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID_Contacts { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public int ID_Visita { get; set; }
        public string Motivo { get; set; }
        public string Nombre_Visitante { get; set; }
        public Nullable<System.DateTime> Fecha_Visita { get; set; }
        public System.TimeSpan Hora_Entrada { get; set; }
        public System.TimeSpan Hora_Salida { get; set; }
        public Nullable<int> ID_Contactss { get; set; }
    }
}
